# Generated by Django 2.0.3 on 2018-06-11 11:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rue', models.CharField(db_column='Rue', max_length=45)),
                ('num', models.CharField(db_column='Num', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Cartebancaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerocarte', models.CharField(db_column='NumeroCarte', max_length=45)),
                ('pin', models.CharField(db_column='PIN', max_length=45)),
                ('montant', models.FloatField(db_column='Montant')),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_column='Nom', max_length=45)),
                ('codepostal', models.CharField(db_column='CodePostal', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='CommuneZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcommune', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sonelgazapp.Commune')),
            ],
        ),
        migrations.CreateModel(
            name='Compteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(default='', max_length=45)),
                ('type', models.CharField(db_column='Type', max_length=1)),
                ('idaddress', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sonelgazapp.Adresse')),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_iduser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='Date')),
                ('montant', models.FloatField(db_column='Montant')),
                ('paye', models.CharField(db_column='Paye', max_length=1)),
                ('idaddress', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sonelgazapp.Adresse')),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='Date', default=datetime.date.today)),
                ('releve', models.IntegerField(db_column='Releve')),
                ('matricule', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sonelgazapp.Compteur')),
            ],
        ),
        migrations.CreateModel(
            name='Raccordement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('G', 'Gaz'), ('E', 'Electricite')], db_column='Type', max_length=1)),
                ('matricule', models.CharField(db_column='Matricule', default='', max_length=45)),
                ('idadresse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sonelgazapp.Adresse')),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('coupure', 'Coupure'), ('erreur_fac', 'Erreur dans la facture'), ('autre', 'Autres')], db_column='Type', max_length=45)),
                ('texte', models.TextField(blank=True, db_column='Texte', null=True)),
                ('prisecharge', models.CharField(db_column='PriseCharge', default='N', max_length=1)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sonelgazapp.Adresse')),
                ('user_iduser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Remise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_column='Type', max_length=2)),
                ('taux', models.FloatField(db_column='Taux')),
                ('date', models.DateField(db_column='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_column='Code', max_length=45)),
                ('coef', models.FloatField(db_column='Coef')),
                ('droitfixe', models.FloatField(db_column='DroitFixe')),
                ('taxehabitation', models.FloatField(db_column='TaxeHabitation')),
                ('timbre', models.FloatField(db_column='Timbre')),
                ('primefixe', models.FloatField(db_column='PrimeFixe')),
                ('tva', models.FloatField(db_column='TVA')),
            ],
        ),
        migrations.CreateModel(
            name='Tranceh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prixunit', models.FloatField(db_column='PrixUnit')),
                ('quantite', models.FloatField(db_column='Quantite')),
                ('idtarif', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sonelgazapp.Tarif')),
            ],
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_column='Nom', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomagence', models.CharField(db_column='NomAgence', max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='zone_idzone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sonelgazapp.Zone'),
        ),
        migrations.AddField(
            model_name='compteur',
            name='tarif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sonelgazapp.Tarif'),
        ),
        migrations.AddField(
            model_name='communezone',
            name='zone_idzone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sonelgazapp.Zone'),
        ),
        migrations.AddField(
            model_name='commune',
            name='wilaya_idwilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sonelgazapp.Wilaya'),
        ),
        migrations.AddField(
            model_name='adresse',
            name='idZone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sonelgazapp.Zone'),
        ),
    ]
